export const TESTNET_URL = 'https://bs-stage.api.onnftverse.com/v1';

export type NFTMiningStatus = 'listed' | 'unlisted' | 'all';

export type NFTFileType = 'text' | 'threeD' | 'image' | 'video';

export type BlockchainName = 'ALGORAND' | 'FLOW';

export type NFTBody = {
    mainAssetId: number; // Asset ID that you want to mint as NFT. This is NFTVerse's internal asset ID.
    supportingAssetIds?: number[]; // List of additional supporting asset IDs that you want to mint in this NFT.
    mainExternalAssetId: string; // Asset ID that you want to mint as NFT. This is the externalAssetId you passed while uploading the asset.
    supportingExternalAssetIds?: string[]; // List of additional supporting external asset IDs that you want to mint in this NFT.
    name: string; // Name of the NFT
    description?: string; // Description of the NFT
    collection: string; // Collection name of the NFT
    displayImageUrl?: string; // Cloudfront URL, or S3 URL or Pinata URL or any other url
    properties?: { key: string; value: string }[]; // List of key-value pairs that you want to add to the NFT
    type: NFTFileType; // Type of the NFT
    recipient: NFTRecipient; // Recipient of the NFT
};

export type NFTRecipient = {
    nftVerseUserId: number; // NFTVerse user ID of the recipient
    externalUserId: number;
    address: string; // Address of the recipient
    blockchain: BlockchainName; // Blockchain of the recipient
};

export type NFTForSale = {
    nftId: number; // NFT ID
    price: number; // Price of the NFT
    priceUnit: 'algo' | 'flow' | 'usd' | 'inr' | 'eth'; // Price unit of the NFT
};

export type WalletUser = {
    externalUserId: number; // External user ID
    email: string; // Email of the user
    mobile: string; // Mobile number of the user
};

export type CustodianWalletUser = {
    email: string; // Email of the user
    address: string; // Address of the user
    seedPhrase: string; // A cluster of random words generated by your crypto wallet when setting it up
};

export type FungibleToken = {
    ftId: number; // Fungible token ID
    blockchainFtId: number; // Blockchain Fungible token ID
    buyerUserId: number; // User ID of the buyer
    blockchain: BlockchainName; // Blockchain of the Fungible token
    amount: number; // Amount of the Fungible token
    externalUserId: number; // External user ID
};
